export const handleApiError = (fn, callback) => (...params) => fn(...params).catch(callback)